import { desc, eq } from "drizzle-orm";
import { getDb } from "./db";
import { stakeholderOrganizations, stakeholderOnboardings, stakeholderOnboardingEvents } from "../drizzle/schema";
import { activationGaps, canTransition, stakeholderPolicies, type OnboardingInput, type OnboardingState } from "./services/stakeholderOnboarding";

export async function createOrganization(legalName: string, stakeholderType: string, registrationReference: string) { const db = await getDb(); if (!db) throw new Error("Database not available"); const [result] = await db.insert(stakeholderOrganizations).values({ legalName, stakeholderType, registrationReference }); return result.insertId; }
export async function listOrganizations() { const db = await getDb(); if (!db) throw new Error("Database not available"); return db.select().from(stakeholderOrganizations).orderBy(desc(stakeholderOrganizations.createdAt)); }
export async function setOrganizationVerification(id: number, verificationStatus: "verified" | "rejected" | "suspended") { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.update(stakeholderOrganizations).set({ verificationStatus }).where(eq(stakeholderOrganizations.id,id)); }
export async function getOrganization(id: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const [row] = await db.select().from(stakeholderOrganizations).where(eq(stakeholderOrganizations.id,id)).limit(1); return row; }

export async function createOnboarding(input: OnboardingInput, userId: number | null, actorUserId: number) {
  const db = await getDb(); if (!db) throw new Error("Database not available"); const initial: OnboardingState = "identity_pending";
  const [result] = await db.insert(stakeholderOnboardings).values({ userId, organizationId: input.organizationId, stakeholderType: input.stakeholderType, displayName: input.displayName, email: input.email, phone: input.phone, state: initial, regionCodes: input.regionCodes, programIds: input.programIds, consentVersion: input.consentVersion, identityEvidenceRefs: input.identityEvidenceRefs, requiresMfa: input.requiresMfa ?? true });
  await db.insert(stakeholderOnboardingEvents).values({ onboardingId: result.insertId, fromState: "invited", toState: initial, actorUserId, reason: "Onboarding application created", evidence: {} }); return result.insertId;
}
export async function listOnboardings() { const db = await getDb(); if (!db) throw new Error("Database not available"); return db.select().from(stakeholderOnboardings).orderBy(desc(stakeholderOnboardings.createdAt)); }
export async function getOnboarding(id: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const [row] = await db.select().from(stakeholderOnboardings).where(eq(stakeholderOnboardings.id,id)).limit(1); return row; }
export async function getEvents(id: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); return db.select().from(stakeholderOnboardingEvents).where(eq(stakeholderOnboardingEvents.onboardingId,id)).orderBy(desc(stakeholderOnboardingEvents.createdAt)); }
export async function transition(id: number, to: OnboardingState, actorUserId: number, reason: string, evidence: Record<string, unknown>) {
  const db = await getDb(); if (!db) throw new Error("Database not available"); const current = await getOnboarding(id); if (!current) throw new Error("Onboarding record not found"); if (!canTransition(current.state,to)) throw new Error(`Invalid transition ${current.state} -> ${to}`); const now = new Date(); const updates: Record<string, unknown> = { state: to };
  const stakeholderType = current.stakeholderType as OnboardingInput["stakeholderType"];
  if (current.state === "identity_pending" && stakeholderPolicies[stakeholderType].organization && to !== "organization_pending" && to !== "rejected") throw new Error("Organization verification cannot be bypassed");
  if (current.state === "organization_pending") { if (!current.organizationId) throw new Error("Organization link is required"); const organization = await getOrganization(current.organizationId); if (!organization || organization.verificationStatus !== "verified") throw new Error("Organization is not verified"); }
  if (current.state === "identity_pending") updates.identityVerifiedAt = now; if (current.state === "organization_pending") updates.organizationVerifiedAt = now; if (current.state === "consent_pending") updates.consentAcceptedAt = now; if (current.state === "scope_pending") updates.scopeApprovedAt = now; if (current.state === "training_pending") updates.trainingCompletedAt = now; if (current.state === "mfa_pending") updates.mfaEnrolledAt = now; if (to === "suspended") updates.suspendedAt = now; if (to === "offboarded") { updates.offboardedAt = now; updates.offboardingReason = reason; }
  if (evidence.safeguardingAttested === true) updates.safeguardingAttestedAt = now; if (evidence.paymentCertified === true) updates.paymentCertifiedAt = now; if (evidence.mfaEnrolled === true) updates.mfaEnrolledAt = now;
  if (to === "active") {
    const gaps = activationGaps(current.stakeholderType as OnboardingInput["stakeholderType"], { stakeholderType: current.stakeholderType as OnboardingInput["stakeholderType"], displayName: current.displayName, email: current.email ?? undefined, phone: current.phone ?? undefined, organizationId: current.organizationId ?? undefined, regionCodes: current.regionCodes, programIds: current.programIds, consentVersion: current.consentVersion ?? undefined, identityEvidenceRefs: current.identityEvidenceRefs, requiresMfa: current.requiresMfa }, { identityVerified: !!current.identityVerifiedAt || current.state === "identity_pending", organizationVerified: !!current.organizationVerifiedAt || current.state === "organization_pending", consentAccepted: !!current.consentAcceptedAt || current.state === "consent_pending", scopeApproved: !!current.scopeApprovedAt || current.state === "scope_pending", trainingCompleted: !!current.trainingCompletedAt || current.state === "training_pending", mfaEnrolled: !!current.mfaEnrolledAt || current.state === "mfa_pending" || evidence.mfaEnrolled===true, safeguardingAttested: !!current.safeguardingAttestedAt || evidence.safeguardingAttested===true, paymentCertified: !!current.paymentCertifiedAt || evidence.paymentCertified===true });
    if (gaps.length) throw new Error(`Activation blocked; missing ${gaps.join(", ")}`);
  }
  await db.update(stakeholderOnboardings).set(updates).where(eq(stakeholderOnboardings.id,id)); await db.insert(stakeholderOnboardingEvents).values({ onboardingId:id, fromState:current.state, toState:to, actorUserId, reason, evidence }); return getOnboarding(id);
}
